#!/bin/bash 

# installed with the following arguments 
#./build_trilinos -DTPL_ENABLE_Netcdf=OFF -DTPL_ENABLE_X11=OFF -DBUILD_SHARED_LIBS=ON -DTrilinos_ENABLE_PyTrilinos=OFF
#  -DTrilinos_ENABLE_PyTrilinos=OFF because v 12.10 dosn't fully support python3
# to change python interpreter -DPYTHON_EXECUTABLE:FILEPATH=<PATH_TO_PYTHON>
# to have tests and examples -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_EXAMPLES=ON
# path to MPI folder has to be adjusted e.g.
# -DMPI_BASE_DIR=/home/hossein/anaconda3/bin 

EXTRA_ARGS=$@

TRILINOS_SRC_DIR=<src_dir>
TRILINOS_BLD_DIR=<build_dir>

cmake \
 -DTPL_ENABLE_MPI=ON \
 -DMPI_BASE_DIR=/usr/bin \
 -DTrilinos_ENABLE_ALL_PACKAGES=ON \
 -DCMAKE_INSTALL_PREFIX=$TRILINOS_BLD_DIR \
 $EXTRA_ARGS \
 $TRILINOS_SRC_DIR 
